# Generated by Django 3.2 on 2023-05-02 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username should only contain letters, digits, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$')]),
        ),
    ]
