# Generated by Django 3.2 on 2023-04-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230427_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(max_length=6, verbose_name='код подтверждения'),
        ),
    ]
