# Generated by Django 3.2 on 2023-05-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['year'], name='year_idx'),
        ),
    ]
